---
# site.yml
- name: SLES CIS Hardening
  hosts: sles_server
  become: true
  gather_facts: false
  
  roles:
    - initial_setup
    - services
    - network
    - logging
    - access_control
    - system_maintenance
    - level2_hardening