---
# site.yml
- name: SLES CIS Hardening
  hosts: sles_server
  become: true
  gather_facts: false

  pre_tasks:
    - name: Install Python 3.11
      raw: |
        zypper --non-interactive refresh && \
        zypper --non-interactive install python311

    - name: Make Python 3.11 the default python3
      raw: |
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && \
        update-alternatives --set python3 /usr/bin/python3.11

    - name: Verify Python version
      raw: python3 --version
      register: python_version

    - name: Display Python version
      debug:
        var: python_version.stdout_lines

    - name: Gather facts
      setup:

  roles:
    - initial_setup
    - services
    - network
    - logging
    - access_control
    - system_maintenance
    - level2_hardening